//! Roc Platform ABI
//!
//! This file defines Zig declarations for the direct symbol ABI used by a Roc platform.
//! It is automatically generated by the Roc glue generator.
//!
//! Hosted argument ownership:
//! - Roc transfers ownership of refcounted arguments to the hosted function.
//! - The hosted function must decref owned refcounted arguments when done.
//! - If the host stores or returns an argument, it must retain or transfer ownership explicitly.
//!
//! Import this file from the platform host and implement the listed hosted symbols
//! with the exact natural C ABI signatures shown below.

const std = @import("std");
const builtin = @import("builtin");

/// Runtime representation of an opaque `Box(T)` value.
pub const RocBox = ?*anyopaque;

/// Host-internal allocator and diagnostic context used by helper functions in this file.
///
/// Compiled Roc code does not receive this value. The real host ABI is the set of direct
/// linker symbols declared below (`roc_alloc`, hosted symbols, and provided entrypoints).
pub const RocHost = extern struct {
    env: *anyopaque,
    roc_alloc: *const fn (*RocHost, usize, usize) callconv(.c) ?*anyopaque,
    roc_dealloc: *const fn (*RocHost, *anyopaque, usize) callconv(.c) void,
    roc_realloc: *const fn (*RocHost, *anyopaque, usize, usize) callconv(.c) ?*anyopaque,
    roc_dbg: *const fn (*RocHost, [*]const u8, usize) callconv(.c) void,
    roc_expect_failed: *const fn (*RocHost, [*]const u8, usize) callconv(.c) void,
    roc_crashed: *const fn (*RocHost, [*]const u8, usize) callconv(.c) void,
};

/// Private erased-callable function pointer stored in `RocErasedCallablePayload`.
pub const RocErasedCallableFn = *const fn (*RocHost, ?[*]u8, ?[*]const u8, ?[*]u8) callconv(.c) void;

/// Final-drop callback for inline erased-callable captures.
pub const RocErasedCallableOnDrop = *const fn (?[*]u8, *RocHost) callconv(.c) void;

/// Payload header for `Box(function)`.
pub const RocErasedCallablePayload = extern struct {
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: ?RocErasedCallableOnDrop,
};

/// Runtime representation of `Box(function)`.
pub const RocErasedCallable = ?[*]u8;

pub const roc_erased_callable_capture_alignment: usize = 16;
pub const roc_erased_callable_payload_alignment: usize = 16;
pub const roc_erased_callable_capture_offset: usize = std.mem.alignForward(usize, @sizeOf(RocErasedCallablePayload), roc_erased_callable_capture_alignment);

pub fn rocErasedCallablePayloadSize(capture_size: usize) usize {
    return roc_erased_callable_capture_offset + capture_size;
}

pub fn rocErasedCallablePayloadPtr(callable: RocErasedCallable) *RocErasedCallablePayload {
    return @ptrCast(@alignCast(callable orelse unreachable));
}

pub fn rocErasedCallableCapturePtr(callable: RocErasedCallable) ?[*]u8 {
    const data = callable orelse return null;
    return data + roc_erased_callable_capture_offset;
}

pub fn rocErasedCallableAllocate(
    roc_host: *RocHost,
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: ?RocErasedCallableOnDrop,
    capture_size: usize,
) RocErasedCallable {
    const ptr_width = @sizeOf(usize);
    const alignment = @max(ptr_width, roc_erased_callable_payload_alignment);
    const extra_bytes = @max(ptr_width, roc_erased_callable_payload_alignment);
    const length = extra_bytes + rocErasedCallablePayloadSize(capture_size);
    const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, length, alignment));
    const data = base + extra_bytes;
    const rc: *isize = @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
    rc.* = 1;
    const payload: *RocErasedCallablePayload = @ptrCast(@alignCast(data));
    payload.* = .{ .callable_fn_ptr = callable_fn_ptr, .on_drop = on_drop };
    return data;
}

/// Payload drop callback for a boxed value.
///
/// The callback receives the boxed payload data pointer and must recursively
/// decref any Roc refcounted values inside the payload. It must not free the
/// box allocation; `decrefBoxWith` and `freeBoxWith` free it after the callback.
pub const RocBoxPayloadDecref = *const fn (?*anyopaque, *RocHost) callconv(.c) void;

/// Increment the refcount of a boxed payload data pointer.
pub fn increfBox(data_ptr: ?*anyopaque, amount: isize) void {
    const data = boxDataPtr(data_ptr) orelse return;
    const rc = boxRefcountPtr(data);
    if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
    _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
}

/// Allocate a Roc box and return a pointer to its payload data.
pub fn allocateBox(
    payload_size: usize,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: *RocHost,
) *anyopaque {
    const ptr_width = @sizeOf(usize);
    const required_space: usize = if (payload_contains_refcounted) (2 * ptr_width) else ptr_width;
    const header_bytes = @max(required_space, payload_alignment);
    const alloc_alignment = @max(ptr_width, payload_alignment);
    const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, header_bytes + payload_size, alloc_alignment));
    const data = base + header_bytes;
    const rc: *isize = @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
    rc.* = 1;
    return @ptrCast(data);
}

/// Decrement a pointer-aligned boxed payload with no Roc refcounted values.
pub fn decrefBox(data_ptr: ?*anyopaque, roc_host: *RocHost) void {
    decrefBoxWith(data_ptr, @alignOf(usize), null, roc_host);
}

/// Increment a boxed function closure.
pub fn increfErasedCallable(callable: RocErasedCallable, amount: isize) void {
    const data = callable orelse return;
    increfBox(@ptrCast(data), amount);
}

/// Decrement a boxed function closure and run its capture drop callback on final release.
pub fn decrefErasedCallable(callable: RocErasedCallable, roc_host: *RocHost) void {
    const data = callable orelse return;
    decrefBoxWith(@ptrCast(data), roc_erased_callable_payload_alignment, &dropErasedCallablePayload, roc_host);
}

fn dropErasedCallablePayload(data_ptr: ?*anyopaque, roc_host: *RocHost) callconv(.c) void {
    const data = data_ptr orelse return;
    const callable: RocErasedCallable = @ptrCast(data);
    const payload = rocErasedCallablePayloadPtr(callable);
    if (payload.on_drop) |on_drop| {
        on_drop(rocErasedCallableCapturePtr(callable), roc_host);
    }
}

/// Decrement a boxed payload and run payload teardown when this is the final ref.
pub fn decrefBoxWith(
    data_ptr: ?*anyopaque,
    payload_alignment: usize,
    payload_decref: ?RocBoxPayloadDecref,
    roc_host: *RocHost,
) void {
    const data = boxDataPtr(data_ptr) orelse return;
    const rc = boxRefcountPtr(data);
    if (rc.* == 0) return; // REFCOUNT_STATIC_DATA

    const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
    if (prev == 1) {
        if (payload_decref) |callback| callback(data_ptr, roc_host);
        freeBoxAllocation(data, payload_alignment, payload_decref != null, roc_host);
    }
}

/// Free a boxed payload allocation immediately after running payload teardown.
pub fn freeBoxWith(
    data_ptr: ?*anyopaque,
    payload_alignment: usize,
    payload_decref: ?RocBoxPayloadDecref,
    roc_host: *RocHost,
) void {
    const data = boxDataPtr(data_ptr) orelse return;
    if (payload_decref) |callback| callback(data_ptr, roc_host);
    freeBoxAllocation(data, payload_alignment, payload_decref != null, roc_host);
}

/// Return true when a boxed payload data pointer has exactly one live ref.
pub fn isUniqueBox(data_ptr: ?*anyopaque) bool {
    const data = boxDataPtr(data_ptr) orelse return true;
    const rc = boxRefcountPtr(data);
    return rc.* == 1;
}

fn boxDataPtr(data_ptr: ?*anyopaque) ?[*]u8 {
    const ptr = data_ptr orelse return null;
    return @ptrCast(ptr);
}

fn boxRefcountPtr(data: [*]u8) *isize {
    return @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
}

fn freeBoxAllocation(
    data: [*]u8,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: *RocHost,
) void {
    const ptr_width = @sizeOf(usize);
    const required_space: usize = if (payload_contains_refcounted) (2 * ptr_width) else ptr_width;
    const header_bytes = @max(required_space, payload_alignment);
    const alloc_alignment = @max(ptr_width, payload_alignment);
    const base: *anyopaque = @ptrFromInt(@intFromPtr(data) - header_bytes);
    roc_host.roc_dealloc(roc_host, base, alloc_alignment);
}

/// A Roc string value. Small strings (up to 23 bytes) are stored inline;
/// larger strings are heap-allocated with a reference count.
///
/// `bytes` is never tagged. Operations, host code, glue code, and object-file
/// relocations can use it directly as the UTF-8 byte pointer for non-small
/// strings. Seamless-slice tagging lives in `capacity_or_alloc_ptr` instead.
/// Big-string capacity is stored shifted left by one bit, so max capacity is
/// essentially `std.math.maxInt(isize)` bytes: about 2 GiB on 32-bit targets
/// and 8 EiB on 64-bit targets.
pub const RocStr = extern struct {
    bytes: ?[*]u8,
    capacity_or_alloc_ptr: usize,
    length: usize,

    const Self = @This();
    const small_string_size = @sizeOf(RocStr);
    const small_str_max_length = small_string_size - 1;
    const small_str_bit: usize = @as(usize, @bitCast(@as(isize, std.math.minInt(isize))));
    const seamless_slice_tag: usize = 1;

    /// Return the string contents as a `[]const u8` slice.
    pub fn asSlice(self: *const Self) []const u8 {
        return self.asU8ptr()[0..self.len()];
    }

    /// Return the length of the string in bytes.
    pub fn len(self: Self) usize {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(&self))[@sizeOf(Self) - 1] ^ 0b1000_0000;
        } else {
            return self.length;
        }
    }

    /// Return true if the string has zero length.
    pub fn isEmpty(self: Self) bool {
        return self.len() == 0;
    }

    /// Return true if this string is stored inline (small string optimization).
    pub fn isSmallStr(self: Self) bool {
        return @as(isize, @bitCast(self.length)) < 0;
    }

    /// Return true if this string is a seamless slice into another allocation.
    pub fn isSeamlessSlice(self: Self) bool {
        return !self.isSmallStr() and (self.capacity_or_alloc_ptr & seamless_slice_tag) != 0;
    }

    /// Return a pointer to the raw UTF-8 bytes.
    pub fn asU8ptr(self: *const Self) [*]const u8 {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(self));
        } else {
            return @as([*]const u8, @ptrCast(self.bytes));
        }
    }

    /// Return an empty RocStr.
    pub fn empty() Self {
        return .{ .bytes = null, .capacity_or_alloc_ptr = 0, .length = small_str_bit };
    }

    /// Create a RocStr from a byte slice, using `roc_host` for heap allocation if needed.
    pub fn fromSlice(slice: []const u8, roc_host: *RocHost) Self {
        if (slice.len < small_string_size) {
            var result = Self.empty();
            const ptr: [*]u8 = @ptrCast(&result);
            @memcpy(ptr[0..slice.len], slice);
            ptr[@sizeOf(Self) - 1] = @as(u8, @intCast(slice.len)) | 0b1000_0000;
            return result;
        } else {
            const ptr_width = @sizeOf(usize);
            const extra_bytes = ptr_width;
            const total = extra_bytes + slice.len;
            const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, total, @alignOf(usize)));
            const data_ptr = base + extra_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            @memcpy(data_ptr[0..slice.len], slice.ptr[0..slice.len]);
            return .{
                .bytes = data_ptr,
                .capacity_or_alloc_ptr = slice.len << 1,
                .length = slice.len,
            };
        }
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    pub fn decref(self: Self, roc_host: *RocHost) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const data_addr = @intFromPtr(alloc_ptr);
        const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
        if (rc.* == 0) return; // REFCOUNT_STATIC_DATA — bytes are in read-only memory
        const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
        if (prev == 1) {
            const ptr_width = @sizeOf(usize);
            const base: *anyopaque = @ptrFromInt(data_addr - ptr_width);
            roc_host.roc_dealloc(roc_host, base, @alignOf(usize));
        }
    }

    /// Increment the reference count by `amount`.
    pub fn incref(self: Self, amount: isize) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const rc: *isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
        _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
    }

    /// Return true if this string has a reference count of exactly one.
    pub fn isUnique(self: Self) bool {
        if (self.isSmallStr()) return true;
        const alloc_ptr = self.getAllocationPtr() orelse return true;
        const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        if (rc.* == 0) return true; // REFCOUNT_STATIC_DATA — treated as unique
        return rc.* == 1;
    }

    fn getAllocationPtr(self: Self) ?[*]u8 {
        if (self.isSeamlessSlice()) {
            return @as(?[*]u8, @ptrFromInt(self.capacity_or_alloc_ptr & ~seamless_slice_tag));
        } else {
            return self.bytes;
        }
    }
};

/// A generic Roc list. Elements are reference-counted and heap-allocated.
///
/// When `elements_refcounted` is true (the default), an extra `ptr_width` bytes
/// are reserved in the allocation header for the element count, matching the Roc
/// runtime's `allocateWithRefcount` layout. Set to `false` for lists of
/// non-refcounted primitives (e.g. `U8`, `I32`).
pub fn RocList(comptime T: type) type {
    return RocListWith(T, true);
}

/// Parameterized list constructor; use `RocList(T)` for refcounted elements.
pub fn RocListWith(comptime T: type, comptime elements_refcounted: bool) type {
    return extern struct {
        elements_ptr: ?[*]T,
        length: usize,
        capacity_or_alloc_ptr: usize,

        const Self = @This();
        const ptr_width = @sizeOf(usize);
        const required_space: usize = if (elements_refcounted) (2 * ptr_width) else ptr_width;
        const header_bytes = @max(required_space, @alignOf(T));
        const alloc_align = @max(ptr_width, @alignOf(T));

        /// Return the list elements as a `[]const T` slice.
        pub fn items(self: Self) []const T {
            if (self.elements_ptr) |ptr| return ptr[0..self.length];
            return &[_]T{};
        }

        /// Return every initialized element in the backing allocation.
        pub fn allocationItems(self: Self) []const T {
            const alloc_ptr = self.getAllocationPtr() orelse return &[_]T{};
            const count = self.allocationElementCount();
            const ptr: [*]const T = @ptrCast(@alignCast(alloc_ptr));
            return ptr[0..count];
        }

        /// Return the number of elements in the list.
        pub fn len(self: Self) usize {
            return self.length;
        }

        /// Return true if the list has zero elements.
        pub fn isEmpty(self: Self) bool {
            return self.length == 0;
        }

        /// Return true if this list is a seamless slice into another allocation.
        /// Slices share the rc slot with their backing allocation; the alloc ptr is
        /// encoded in `capacity_or_alloc_ptr` with the low bit set.
        pub fn isSeamlessSlice(self: Self) bool {
            return (self.capacity_or_alloc_ptr & 1) != 0;
        }

        /// Return an empty RocList.
        pub fn empty() Self {
            return .{ .elements_ptr = null, .length = 0, .capacity_or_alloc_ptr = 0 };
        }

        /// Resolve `self` to the start of its backing allocation (the element block
        /// just after the rc slot). Returns `null` for empty lists. Handles both
        /// whole-backing and seamless-slice forms.
        fn getAllocationPtr(self: Self) ?[*]u8 {
            if (self.isSeamlessSlice()) {
                return @as(?[*]u8, @ptrFromInt(self.capacity_or_alloc_ptr & ~@as(usize, 1)));
            }
            const ptr = self.elements_ptr orelse return null;
            return @ptrCast(ptr);
        }

        fn allocationElementCount(self: Self) usize {
            if (self.isSeamlessSlice() and elements_refcounted) {
                const alloc_ptr = self.getAllocationPtr() orelse return 0;
                const ptr: [*]const usize = @ptrCast(@alignCast(alloc_ptr));
                return (ptr - 2)[0];
            }
            return self.length;
        }

        /// Allocate a new list with space for `length` elements.
        pub fn allocate(length: usize, roc_host: *RocHost) Self {
            if (length == 0) return empty();
            const data_bytes = length * @sizeOf(T);
            const total = data_bytes + header_bytes;
            const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, total, alloc_align));
            const data_ptr = base + header_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            return .{
                .elements_ptr = @ptrCast(@alignCast(data_ptr)),
                .length = length,
                .capacity_or_alloc_ptr = length << 1,
            };
        }

        /// Create a RocList from a slice, copying elements into a new allocation.
        pub fn fromSlice(slice: []const T, roc_host: *RocHost) Self {
            if (slice.len == 0) return empty();
            const list = allocate(slice.len, roc_host);
            const dest: [*]u8 = @ptrCast(list.elements_ptr.?);
            const src: [*]const u8 = @ptrCast(slice.ptr);
            @memcpy(dest[0 .. slice.len * @sizeOf(T)], src[0 .. slice.len * @sizeOf(T)]);
            return list;
        }

        /// Decrement the reference count; frees the allocation when it reaches zero.
        pub fn decref(self: Self, roc_host: *RocHost) void {
            const alloc_ptr = self.getAllocationPtr() orelse return;
            const data_addr = @intFromPtr(alloc_ptr);
            const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
            if (rc.* == 0) return; // REFCOUNT_STATIC_DATA — bytes are in read-only memory
            const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
            if (prev == 1) {
                const base: *anyopaque = @ptrFromInt(data_addr - header_bytes);
                roc_host.roc_dealloc(roc_host, base, alloc_align);
            }
        }

        /// Increment the reference count by `amount`.
        pub fn incref(self: Self, amount: isize) void {
            const alloc_ptr = self.getAllocationPtr() orelse return;
            const rc: *isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
            _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
        }

        /// Return true if this list has a reference count of exactly one.
        pub fn isUnique(self: Self) bool {
            const alloc_ptr = self.getAllocationPtr() orelse return true;
            const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            if (rc.* == 0) return true; // REFCOUNT_STATIC_DATA — treated as unique
            return rc.* == 1;
        }

        /// Return true if this list's allocation has exactly one counted ref.
        pub fn hasOneRef(self: Self) bool {
            const alloc_ptr = self.getAllocationPtr() orelse return false;
            const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            return rc.* == 1;
        }
    };
}

/// Minimal I/O abstraction for Roc platform hosts.
///
/// Provides stderr output and fatal-error handling that can be routed
/// to different backends (POSIX, freestanding/WASM, custom).
///
/// Use `RocIo.default()` for most platforms; inject a custom vtable for
/// environments without POSIX stdio (e.g. WASM freestanding).
pub const RocIo = struct {
    ctx: ?*anyopaque,
    vtable: *const VTable,

    pub const VTable = struct {
        /// Write to stderr. Best-effort: errors are silently ignored.
        writeStderr: *const fn (?*anyopaque, []const u8) void,
        /// Terminate the process or trap. Must not return.
        onFatal: *const fn (?*anyopaque) noreturn,
    };

    /// Write `data` to stderr (best-effort).
    pub fn writeStderr(self: RocIo, data: []const u8) void {
        self.vtable.writeStderr(self.ctx, data);
    }

    /// Terminate the process or trap. Does not return.
    pub fn onFatal(self: RocIo) noreturn {
        self.vtable.onFatal(self.ctx);
    }

    /// Native (POSIX) implementation: writes to stderr, exits with code 1.
    pub fn native() RocIo {
        return .{ .ctx = null, .vtable = &native_vtable };
    }

    /// Freestanding implementation: no-op stderr, @trap() on fatal.
    pub fn freestanding() RocIo {
        return .{ .ctx = null, .vtable = &freestanding_vtable };
    }

    /// Select the appropriate implementation for the current build target.
    pub fn default() RocIo {
        if (comptime builtin.os.tag == .freestanding) {
            return freestanding();
        }
        return native();
    }

    fn nativeWriteStderr(_: ?*anyopaque, data: []const u8) void {
        std.Io.File.stderr().writeStreamingAll(std.Io.Threaded.global_single_threaded.io(), data) catch {};
    }

    fn nativeOnFatal(_: ?*anyopaque) noreturn {
        std.process.exit(1);
    }

    fn freestandingWriteStderr(_: ?*anyopaque, _: []const u8) void {}

    fn freestandingOnFatal(_: ?*anyopaque) noreturn {
        @trap();
    }

    const native_vtable: VTable = .{
        .writeStderr = &nativeWriteStderr,
        .onFatal = &nativeOnFatal,
    };

    const freestanding_vtable: VTable = .{
        .writeStderr = &freestandingWriteStderr,
        .onFatal = &freestandingOnFatal,
    };
};

/// Host environment passed to the Roc runtime.
///
/// Bundles the allocator and I/O backend used by DefaultAllocators
/// and DefaultHandlers.
pub const RocEnv = struct {
    allocator: std.mem.Allocator,
    roc_io: RocIo,
};

/// Element type for TigerBeetle.CreateAccountResult
pub const TigerBeetleCreateAccountResult = extern struct {
    timestamp: u64,
    status: u32,
    _pad0: [4]u8,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(TigerBeetleCreateAccountResult) != 16) @compileError("TigerBeetleCreateAccountResult size mismatch");
        if (@alignOf(TigerBeetleCreateAccountResult) != 8) @compileError("TigerBeetleCreateAccountResult alignment mismatch");
    }
}

/// Element type for TigerBeetle.Account
pub const TigerBeetleAccount = extern struct {
    id: u128,
    debits_pending: u128,
    debits_posted: u128,
    credits_pending: u128,
    credits_posted: u128,
    user_data_128: u128,
    user_data_64: u64,
    user_data_32: u32,
    _pad0: [4]u8,
    ledger: u32,
    code: u16,
    flags: u16,
    timestamp: u64,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(TigerBeetleAccount) != 128) @compileError("TigerBeetleAccount size mismatch");
        if (@alignOf(TigerBeetleAccount) != 16) @compileError("TigerBeetleAccount alignment mismatch");
    }
}

/// Element type for TigerBeetle.CreateTransferResult
pub const TigerBeetleCreateTransferResult = extern struct {
    timestamp: u64,
    status: u32,
    _pad0: [4]u8,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(TigerBeetleCreateTransferResult) != 16) @compileError("TigerBeetleCreateTransferResult size mismatch");
        if (@alignOf(TigerBeetleCreateTransferResult) != 8) @compileError("TigerBeetleCreateTransferResult alignment mismatch");
    }
}

/// Element type for TigerBeetle.Transfer
pub const TigerBeetleTransfer = extern struct {
    id: u128,
    debit_account_id: u128,
    credit_account_id: u128,
    amount: u128,
    pending_id: u128,
    user_data_128: u128,
    user_data_64: u64,
    user_data_32: u32,
    timeout: u32,
    ledger: u32,
    code: u16,
    flags: u16,
    timestamp: u64,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(TigerBeetleTransfer) != 128) @compileError("TigerBeetleTransfer size mismatch");
        if (@alignOf(TigerBeetleTransfer) != 16) @compileError("TigerBeetleTransfer alignment mismatch");
    }
}

/// Element type for TigerBeetle.AccountFilter
pub const TigerBeetleAccountFilter = extern struct {
    account_id: u128,
    user_data_128: u128,
    user_data_64: u64,
    user_data_32: u32,
    code: u16,
    _pad0: [58]u8,
    timestamp_min: u64,
    timestamp_max: u64,
    limit: u32,
    flags: u32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(TigerBeetleAccountFilter) != 128) @compileError("TigerBeetleAccountFilter size mismatch");
        if (@alignOf(TigerBeetleAccountFilter) != 16) @compileError("TigerBeetleAccountFilter alignment mismatch");
    }
}

/// Element type for __AnonStruct20
pub const __AnonStruct20 = extern struct {
    _0: u16,
    _1: u16,
    _10: u16,
    _11: u16,
    _12: u16,
    _13: u16,
    _14: u16,
    _15: u16,
    _16: u16,
    _17: u16,
    _18: u16,
    _19: u16,
    _2: u16,
    _20: u16,
    _21: u16,
    _22: u16,
    _23: u16,
    _24: u16,
    _25: u16,
    _26: u16,
    _27: u16,
    _28: u16,
    _3: u16,
    _4: u16,
    _5: u16,
    _6: u16,
    _7: u16,
    _8: u16,
    _9: u16,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct20) != 58) @compileError("__AnonStruct20 size mismatch");
        if (@alignOf(__AnonStruct20) != 2) @compileError("__AnonStruct20 alignment mismatch");
    }
}

/// Element type for TigerBeetle.AccountBalance
pub const TigerBeetleAccountBalance = extern struct {
    debits_pending: u128,
    debits_posted: u128,
    credits_pending: u128,
    credits_posted: u128,
    timestamp: u64,
    _pad0: [56]u8,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(TigerBeetleAccountBalance) != 128) @compileError("TigerBeetleAccountBalance size mismatch");
        if (@alignOf(TigerBeetleAccountBalance) != 16) @compileError("TigerBeetleAccountBalance alignment mismatch");
    }
}

/// Element type for __AnonStruct23
pub const __AnonStruct23 = extern struct {
    _0: u64,
    _1: u64,
    _2: u64,
    _3: u64,
    _4: u64,
    _5: u64,
    _6: u64,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct23) != 56) @compileError("__AnonStruct23 size mismatch");
        if (@alignOf(__AnonStruct23) != 8) @compileError("__AnonStruct23 alignment mismatch");
    }
}

/// Element type for TigerBeetle.QueryFilter
pub const TigerBeetleQueryFilter = extern struct {
    user_data_128: u128,
    user_data_64: u64,
    user_data_32: u32,
    ledger: u32,
    code: u16,
    _pad0: [6]u8,
    timestamp_min: u64,
    timestamp_max: u64,
    limit: u32,
    flags: u32,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(TigerBeetleQueryFilter) != 64) @compileError("TigerBeetleQueryFilter size mismatch");
        if (@alignOf(TigerBeetleQueryFilter) != 16) @compileError("TigerBeetleQueryFilter alignment mismatch");
    }
}

/// Element type for __AnonStruct25
pub const __AnonStruct25 = extern struct {
    _0: u16,
    _1: u16,
    _2: u16,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct25) != 6) @compileError("__AnonStruct25 size mismatch");
        if (@alignOf(__AnonStruct25) != 2) @compileError("__AnonStruct25 alignment mismatch");
    }
}

/// Element type for __AnonStruct28
pub const __AnonStruct28 = extern struct {
    cluster_id: u128,
    addresses: RocStr,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct28) != 48) @compileError("__AnonStruct28 size mismatch");
        if (@alignOf(__AnonStruct28) != 16) @compileError("__AnonStruct28 alignment mismatch");
    }
}

/// Tag discriminant for Try.
pub const TryTag = enum(u8) {
    Err = 0,
    Ok = 1,
};

/// Tag union: Try
pub const Try = extern struct {
    payload: extern union {
        err: TigerBeetleClientInitErr,
        ok: void,
    },
    tag: TryTag,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(Try) != 2) @compileError("Try size mismatch");
        if (@alignOf(Try) != 1) @compileError("Try alignment mismatch");
    }
}

/// Tag union: TigerBeetle.Client.InitErr
pub const TigerBeetleClientInitErr = enum(u8) {
    address_invalid = 0,
    address_limit_exceeded = 1,
    network_subsystem = 2,
    out_of_memory = 3,
    system_resources = 4,
    unexpected = 5,
};

/// Arguments for Stderr.line!
/// Roc signature: Str => {}
/// Refcounted fields are owned by the hosted function.
pub const StderrLineArgs = extern struct {
    arg0: RocStr,
};

/// Arguments for Stdout.line!
/// Roc signature: Str => {}
/// Refcounted fields are owned by the hosted function.
pub const StdoutLineArgs = extern struct {
    arg0: RocStr,
};

/// Arguments for TigerBeetle.Client.create_accounts!
/// Roc signature: TigerBeetle.Client, List(TigerBeetle.Account) => List(TigerBeetle.CreateAccountResult)
/// Refcounted fields are owned by the hosted function.
pub const TigerBeetleClientCreate_accountsArgs = extern struct {
    arg0: void,
    arg1: RocListWith(TigerBeetleAccount, false),
};

/// Arguments for TigerBeetle.Client.create_transfers!
/// Roc signature: TigerBeetle.Client, List(TigerBeetle.Transfer) => List(TigerBeetle.CreateTransferResult)
/// Refcounted fields are owned by the hosted function.
pub const TigerBeetleClientCreate_transfersArgs = extern struct {
    arg0: void,
    arg1: RocListWith(TigerBeetleTransfer, false),
};

/// Arguments for TigerBeetle.Client.get_account_balances!
/// Roc signature: TigerBeetle.Client, TigerBeetle.AccountFilter => List(TigerBeetle.AccountBalance)
/// Refcounted fields are owned by the hosted function.
pub const TigerBeetleClientGet_account_balancesArgs = extern struct {
    arg0: void,
    arg1: TigerBeetleAccountFilter,
};

/// Arguments for TigerBeetle.Client.get_account_transfers!
/// Roc signature: TigerBeetle.Client, TigerBeetle.AccountFilter => List(TigerBeetle.Transfer)
/// Refcounted fields are owned by the hosted function.
pub const TigerBeetleClientGet_account_transfersArgs = extern struct {
    arg0: void,
    arg1: TigerBeetleAccountFilter,
};

/// Arguments for TigerBeetle.Client.init!
/// Roc signature: { addresses : Str, cluster_id : U128 } => Try(TigerBeetle.Client, TigerBeetle.Client.InitErr)
/// Refcounted fields are owned by the hosted function.
pub const TigerBeetleClientInitArgs = extern struct {
    cluster_id: u128,
    addresses: RocStr,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(TigerBeetleClientInitArgs) != 48) @compileError("TigerBeetleClientInitArgs size mismatch");
        if (@alignOf(TigerBeetleClientInitArgs) != 16) @compileError("TigerBeetleClientInitArgs alignment mismatch");
    }
}

/// Arguments for TigerBeetle.Client.lookup_accounts!
/// Roc signature: TigerBeetle.Client, List(U128) => List(TigerBeetle.Account)
/// Refcounted fields are owned by the hosted function.
pub const TigerBeetleClientLookup_accountsArgs = extern struct {
    arg0: void,
    arg1: RocListWith(u128, false),
};

/// Arguments for TigerBeetle.Client.lookup_transfers!
/// Roc signature: TigerBeetle.Client, List(U128) => List(TigerBeetle.Transfer)
/// Refcounted fields are owned by the hosted function.
pub const TigerBeetleClientLookup_transfersArgs = extern struct {
    arg0: void,
    arg1: RocListWith(u128, false),
};

/// Arguments for TigerBeetle.Client.query_accounts!
/// Roc signature: TigerBeetle.Client, TigerBeetle.QueryFilter => List(TigerBeetle.Account)
/// Refcounted fields are owned by the hosted function.
pub const TigerBeetleClientQuery_accountsArgs = extern struct {
    arg0: void,
    arg1: TigerBeetleQueryFilter,
};

/// Arguments for TigerBeetle.Client.query_transfers!
/// Roc signature: TigerBeetle.Client, TigerBeetle.QueryFilter => List(TigerBeetle.Transfer)
/// Refcounted fields are owned by the hosted function.
pub const TigerBeetleClientQuery_transfersArgs = extern struct {
    arg0: void,
    arg1: TigerBeetleQueryFilter,
};

// =============================================================================
// Generated Refcount Helpers
// =============================================================================

/// Recursively decrement Roc-owned fields in TigerBeetleCreateAccountResult.
pub fn decrefTigerBeetleCreateAccountResult(value: TigerBeetleCreateAccountResult, roc_host: *RocHost) void {
    _ = value;
    _ = roc_host;
}

/// Increment Roc-owned fields in TigerBeetleCreateAccountResult.
pub fn increfTigerBeetleCreateAccountResult(value: TigerBeetleCreateAccountResult, amount: isize) void {
    _ = value;
    _ = amount;
}

/// Recursively decrement Roc-owned fields in TigerBeetleAccount.
pub fn decrefTigerBeetleAccount(value: TigerBeetleAccount, roc_host: *RocHost) void {
    _ = value;
    _ = roc_host;
}

/// Increment Roc-owned fields in TigerBeetleAccount.
pub fn increfTigerBeetleAccount(value: TigerBeetleAccount, amount: isize) void {
    _ = value;
    _ = amount;
}

/// Recursively decrement Roc-owned fields in TigerBeetleCreateTransferResult.
pub fn decrefTigerBeetleCreateTransferResult(value: TigerBeetleCreateTransferResult, roc_host: *RocHost) void {
    _ = value;
    _ = roc_host;
}

/// Increment Roc-owned fields in TigerBeetleCreateTransferResult.
pub fn increfTigerBeetleCreateTransferResult(value: TigerBeetleCreateTransferResult, amount: isize) void {
    _ = value;
    _ = amount;
}

/// Recursively decrement Roc-owned fields in TigerBeetleTransfer.
pub fn decrefTigerBeetleTransfer(value: TigerBeetleTransfer, roc_host: *RocHost) void {
    _ = value;
    _ = roc_host;
}

/// Increment Roc-owned fields in TigerBeetleTransfer.
pub fn increfTigerBeetleTransfer(value: TigerBeetleTransfer, amount: isize) void {
    _ = value;
    _ = amount;
}

/// Recursively decrement Roc-owned fields in TigerBeetleAccountFilter.
pub fn decrefTigerBeetleAccountFilter(value: TigerBeetleAccountFilter, roc_host: *RocHost) void {
    _ = value;
    _ = roc_host;
}

/// Increment Roc-owned fields in TigerBeetleAccountFilter.
pub fn increfTigerBeetleAccountFilter(value: TigerBeetleAccountFilter, amount: isize) void {
    _ = value;
    _ = amount;
}

/// Recursively decrement Roc-owned fields in __AnonStruct20.
pub fn decref__AnonStruct20(value: __AnonStruct20, roc_host: *RocHost) void {
    _ = value;
    _ = roc_host;
}

/// Increment Roc-owned fields in __AnonStruct20.
pub fn incref__AnonStruct20(value: __AnonStruct20, amount: isize) void {
    _ = value;
    _ = amount;
}

/// Recursively decrement Roc-owned fields in TigerBeetleAccountBalance.
pub fn decrefTigerBeetleAccountBalance(value: TigerBeetleAccountBalance, roc_host: *RocHost) void {
    _ = value;
    _ = roc_host;
}

/// Increment Roc-owned fields in TigerBeetleAccountBalance.
pub fn increfTigerBeetleAccountBalance(value: TigerBeetleAccountBalance, amount: isize) void {
    _ = value;
    _ = amount;
}

/// Recursively decrement Roc-owned fields in __AnonStruct23.
pub fn decref__AnonStruct23(value: __AnonStruct23, roc_host: *RocHost) void {
    _ = value;
    _ = roc_host;
}

/// Increment Roc-owned fields in __AnonStruct23.
pub fn incref__AnonStruct23(value: __AnonStruct23, amount: isize) void {
    _ = value;
    _ = amount;
}

/// Recursively decrement Roc-owned fields in TigerBeetleQueryFilter.
pub fn decrefTigerBeetleQueryFilter(value: TigerBeetleQueryFilter, roc_host: *RocHost) void {
    _ = value;
    _ = roc_host;
}

/// Increment Roc-owned fields in TigerBeetleQueryFilter.
pub fn increfTigerBeetleQueryFilter(value: TigerBeetleQueryFilter, amount: isize) void {
    _ = value;
    _ = amount;
}

/// Recursively decrement Roc-owned fields in __AnonStruct25.
pub fn decref__AnonStruct25(value: __AnonStruct25, roc_host: *RocHost) void {
    _ = value;
    _ = roc_host;
}

/// Increment Roc-owned fields in __AnonStruct25.
pub fn incref__AnonStruct25(value: __AnonStruct25, amount: isize) void {
    _ = value;
    _ = amount;
}

/// Recursively decrement Roc-owned payloads in Try.
pub fn decrefTry(value: Try, roc_host: *RocHost) void {
    switch (value.tag) {
        .Err => {
            decrefTigerBeetleClientInitErr(value.payload.err, roc_host);
        },
        .Ok => {},
    }
}

/// Increment Roc-owned payloads in Try.
pub fn increfTry(value: Try, amount: isize) void {
    switch (value.tag) {
        .Err => {
            increfTigerBeetleClientInitErr(value.payload.err, amount);
        },
        .Ok => {},
    }
}

/// Recursively decrement Roc-owned payloads in TigerBeetleClientInitErr.
pub fn decrefTigerBeetleClientInitErr(value: TigerBeetleClientInitErr, roc_host: *RocHost) void {
    _ = roc_host;
    _ = value;
}

/// Increment Roc-owned payloads in TigerBeetleClientInitErr.
pub fn increfTigerBeetleClientInitErr(value: TigerBeetleClientInitErr, amount: isize) void {
    _ = value;
    _ = amount;
}

/// Recursively decrement Roc-owned fields in __AnonStruct28.
pub fn decref__AnonStruct28(value: __AnonStruct28, roc_host: *RocHost) void {
    value.addresses.decref(roc_host);
}

/// Increment Roc-owned fields in __AnonStruct28.
pub fn incref__AnonStruct28(value: __AnonStruct28, amount: isize) void {
    value.addresses.incref(amount);
}

// =============================================================================
// Runtime Symbols
//
// The host defines these linker symbols. Compiled Roc code calls them directly.
// =============================================================================

pub extern fn roc_alloc(length: usize, alignment: usize) callconv(.c) ?*anyopaque;
pub extern fn roc_dealloc(ptr: *anyopaque, alignment: usize) callconv(.c) void;
pub extern fn roc_realloc(ptr: *anyopaque, new_length: usize, alignment: usize) callconv(.c) ?*anyopaque;
pub extern fn roc_dbg(bytes: [*]const u8, len: usize) callconv(.c) void;
pub extern fn roc_expect_failed(bytes: [*]const u8, len: usize) callconv(.c) void;
pub extern fn roc_crashed(bytes: [*]const u8, len: usize) callconv(.c) void;

// =============================================================================
// Hosted Symbols
//
// The platform host must export these symbols with the exact direct C ABI signatures.
// Refcounted arguments are owned by the hosted function.
// =============================================================================

/// Hosted symbol for Host.posix_time!
/// Roc signature: {} => I128
pub extern fn roc_host_posix_time() callconv(.c) i128;

/// Hosted symbol for Stderr.line!
/// Roc signature: Str => {}
pub extern fn roc_stderr_line(arg0: RocStr) callconv(.c) void;

/// Hosted symbol for Stdin.line!
/// Roc signature: {} => Str
pub extern fn roc_stdin_line() callconv(.c) RocStr;

/// Hosted symbol for Stdout.line!
/// Roc signature: Str => {}
pub extern fn roc_stdout_line(arg0: RocStr) callconv(.c) void;

/// Hosted symbol for TigerBeetle.Client.create_accounts!
/// Roc signature: TigerBeetle.Client, List(TigerBeetle.Account) => List(TigerBeetle.CreateAccountResult)
pub extern fn roc_tb_create_accounts(arg0: RocListWith(TigerBeetleAccount, false)) callconv(.c) RocListWith(TigerBeetleCreateAccountResult, false);

/// Hosted symbol for TigerBeetle.Client.create_transfers!
/// Roc signature: TigerBeetle.Client, List(TigerBeetle.Transfer) => List(TigerBeetle.CreateTransferResult)
pub extern fn roc_tb_create_transfers(arg0: RocListWith(TigerBeetleTransfer, false)) callconv(.c) RocListWith(TigerBeetleCreateTransferResult, false);

/// Hosted symbol for TigerBeetle.Client.get_account_balances!
/// Roc signature: TigerBeetle.Client, TigerBeetle.AccountFilter => List(TigerBeetle.AccountBalance)
pub extern fn roc_tb_get_account_balances(arg0: TigerBeetleAccountFilter) callconv(.c) RocListWith(TigerBeetleAccountBalance, false);

/// Hosted symbol for TigerBeetle.Client.get_account_transfers!
/// Roc signature: TigerBeetle.Client, TigerBeetle.AccountFilter => List(TigerBeetle.Transfer)
pub extern fn roc_tb_get_account_transfers(arg0: TigerBeetleAccountFilter) callconv(.c) RocListWith(TigerBeetleTransfer, false);

/// Hosted symbol for TigerBeetle.Client.init!
/// Roc signature: { addresses : Str, cluster_id : U128 } => Try(TigerBeetle.Client, TigerBeetle.Client.InitErr)
pub extern fn roc_tb_client_init(arg0: TigerBeetleClientInitArgs) callconv(.c) Try;

/// Hosted symbol for TigerBeetle.Client.lookup_accounts!
/// Roc signature: TigerBeetle.Client, List(U128) => List(TigerBeetle.Account)
pub extern fn roc_tb_lookup_accounts(arg0: RocListWith(u128, false)) callconv(.c) RocListWith(TigerBeetleAccount, false);

/// Hosted symbol for TigerBeetle.Client.lookup_transfers!
/// Roc signature: TigerBeetle.Client, List(U128) => List(TigerBeetle.Transfer)
pub extern fn roc_tb_lookup_transfers(arg0: RocListWith(u128, false)) callconv(.c) RocListWith(TigerBeetleTransfer, false);

/// Hosted symbol for TigerBeetle.Client.query_accounts!
/// Roc signature: TigerBeetle.Client, TigerBeetle.QueryFilter => List(TigerBeetle.Account)
pub extern fn roc_tb_query_accounts(arg0: TigerBeetleQueryFilter) callconv(.c) RocListWith(TigerBeetleAccount, false);

/// Hosted symbol for TigerBeetle.Client.query_transfers!
/// Roc signature: TigerBeetle.Client, TigerBeetle.QueryFilter => List(TigerBeetle.Transfer)
pub extern fn roc_tb_query_transfers(arg0: TigerBeetleQueryFilter) callconv(.c) RocListWith(TigerBeetleTransfer, false);

/// Hosted symbol for TigerBeetle.id!
/// Roc signature: {} => U128
pub extern fn roc_tb_id() callconv(.c) u128;

/// Default memory management functions for Roc platforms.
///
/// Uses `RocEnv.allocator` for allocation. Each allocation prepends
/// size metadata so that dealloc/realloc can recover the original
/// allocation size (required because `roc_dealloc` receives no length).
pub const DefaultAllocators = struct {
    /// Allocate memory for the Roc runtime.
    pub fn rocAlloc(roc_host: *RocHost, length: usize, alignment: usize) callconv(.c) ?*anyopaque {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;
        const total_size = length + size_storage_bytes;

        const base_ptr = allocator.rawAlloc(total_size, align_enum, @returnAddress()) orelse {
            env.roc_io.writeStderr("roc_alloc: out of memory\n");
            env.roc_io.onFatal();
        };

        // Store total size immediately before the user data pointer
        const size_ptr: *usize = @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes - @sizeOf(usize));
        size_ptr.* = total_size;

        return @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes);
    }

    /// Free memory previously allocated by `rocAlloc`.
    pub fn rocDealloc(roc_host: *RocHost, ptr: *anyopaque, alignment: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;

        const size_ptr: *const usize = @ptrFromInt(@intFromPtr(ptr) - @sizeOf(usize));
        const total_size = size_ptr.*;

        const base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(ptr) - size_storage_bytes);
        const slice = base_ptr[0..total_size];
        allocator.rawFree(slice, align_enum, @returnAddress());
    }

    /// Reallocate memory, copying existing data to the new allocation.
    pub fn rocRealloc(roc_host: *RocHost, ptr: *anyopaque, new_length: usize, alignment: usize) callconv(.c) ?*anyopaque {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;

        // Read old size from metadata
        const old_size_ptr: *const usize = @ptrFromInt(@intFromPtr(ptr) - @sizeOf(usize));
        const old_total_size = old_size_ptr.*;
        const old_base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(ptr) - size_storage_bytes);

        // Allocate new block
        const new_total_size = new_length + size_storage_bytes;
        const new_base_ptr = allocator.rawAlloc(new_total_size, align_enum, @returnAddress()) orelse {
            env.roc_io.writeStderr("roc_realloc: out of memory\n");
            env.roc_io.onFatal();
        };

        // Copy old user data to new location
        const old_user_data_size = old_total_size - size_storage_bytes;
        const copy_size = @min(old_user_data_size, new_length);
        const new_user_ptr: [*]u8 = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes);
        const old_user_ptr: [*]const u8 = @ptrCast(ptr);
        @memcpy(new_user_ptr[0..copy_size], old_user_ptr[0..copy_size]);

        // Free old allocation
        allocator.rawFree(old_base_ptr[0..old_total_size], align_enum, @returnAddress());

        // Store new size and return user pointer
        const new_size_ptr: *usize = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes - @sizeOf(usize));
        new_size_ptr.* = new_total_size;
        return new_user_ptr;
    }
};

/// Default handlers for dbg, expect-failed, and crash.
///
/// Routes output through `RocEnv.roc_io` for platform portability.
pub const DefaultHandlers = struct {
    /// Print a `dbg` expression to stderr.
    pub fn rocDbg(roc_host: *RocHost, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        env.roc_io.writeStderr("[ROC DBG] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
    }

    /// Print a failed `expect` to stderr.
    pub fn rocExpectFailed(roc_host: *RocHost, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        env.roc_io.writeStderr("[ROC EXPECT] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
    }

    /// Print a `crash` message to stderr and terminate.
    pub fn rocCrashed(roc_host: *RocHost, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        env.roc_io.writeStderr("[ROC CRASHED] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
        env.roc_io.onFatal();
    }
};

/// Create a host-internal helper context with default memory management and handlers.
///
/// This is only for helper functions in this generated file. It is not passed to
/// compiled Roc code, which uses the direct symbol ABI declared above.
///
/// Example:
/// ```zig
/// var env = RocEnv{ .allocator = gpa.allocator(), .roc_io = RocIo.default() };
/// var roc_host = makeRocHost(&env);
/// ```
pub fn makeRocHost(env: *RocEnv) RocHost {
    return .{
        .env = @ptrCast(env),
        .roc_alloc = &DefaultAllocators.rocAlloc,
        .roc_dealloc = &DefaultAllocators.rocDealloc,
        .roc_realloc = &DefaultAllocators.rocRealloc,
        .roc_dbg = &DefaultHandlers.rocDbg,
        .roc_expect_failed = &DefaultHandlers.rocExpectFailed,
        .roc_crashed = &DefaultHandlers.rocCrashed,
    };
}

// =============================================================================
// Provided Symbols
//
// Roc exports these symbols from the app with their natural C ABI signatures.
// =============================================================================

/// Entrypoint: main_for_host!
pub extern fn roc_main(arg0: RocList(RocStr)) callconv(.c) i32;
