name: CI

on:
  pull_request:

jobs:
  build:
    name: zig build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15-intel
          - macos-15
          - ubuntu-22.04
          - ubuntu-24.04-arm
          - windows-2022
          - windows-2025
          # TODO: re-enable windows-11-arm after https://codeberg.org/ziglang/zig/issues/31865 is fixed.
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Zig
        uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # ratchet:mlugg/setup-zig@v2.2.1
        with:
          version: 0.16.0
          use-cache: false

      - name: Run all tests
        uses: roc-lang/roc/.github/actions/flaky-retry@3d0fdde9ae6ffb5ef411f8c8c2fc2cdce22a74fe
        with:
          command: bash ci/all_tests.sh
          error_string_contains: "build.zig.zon"
